version: 2

models:
  - name: session_summary
    description: "Analytics model for stock session data"
    columns:
      - name: stock_symbol
        description: "Unique identifier for each stock"
      - name: start_date
        description: "Earliest trading date in the session"
      - name: end_date
        description: "Latest trading date in the session"
      - name: trading_days
        description: "Number of distinct trading days"
      - name: average_close_price
        description: "Average closing price during the session"
      - name: lowest_close_price
        description: "Lowest closing price during the session"
      - name: highest_close_price
        description: "Highest closing price during the session"
      - name: total_volume
        description: "Total volume traded during the session"
      - name: ts
        description: "Timestamp for tracking updates (used in snapshots)"
        tests:
          - not_null
